# Generated by Django 5.0.6 on 2026-05-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='delivery_proof',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
    ]
