# Generated by Django 5.0.6 on 2026-05-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dispatchorder_delivery_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='acknowledgement_receipt',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
