# Generated by Django 5.0.14 on 2026-05-28 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_acknowledgement_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('coc', 'Certificate of Compliance (COC)'), ('cnc', 'Certificate of Non-Coverage (CNC)'), ('bfp', 'BFP Certificate'), ('business_permit', 'Business Permit'), ('dti', 'DTI Permit'), ('plate_number', 'Plate Number'), ('cr', 'Certificate of Registration (CR)'), ('or', 'Official Receipt (OR)'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='customer_docs/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
